name: Build, Wiz Scan, and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This magical line adds the manual trigger button!

# Required to push to GitHub Container Registry
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: my-app:latest
  REGISTRY: ghcr.io

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Download Wiz CLI v1
        run: curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI Container Image Scan
        # Passing credentials directly as environment variables to the scan step
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: ./wizcli scan container-image ${{ env.IMAGE_NAME }} --policy "phoebe vulnerabilities policy" --tag wizignore=yes

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/my-app
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:latest
          docker push $IMAGE_ID:latest